### YamlMime:ManagedReference
items:
- uid: ECS.Resources.InputConfigLoader.JoystickInputJson
  commentId: T:ECS.Resources.InputConfigLoader.JoystickInputJson
  id: InputConfigLoader.JoystickInputJson
  parent: ECS.Resources
  children:
  - ECS.Resources.InputConfigLoader.JoystickInputJson.JoystickDirection
  - ECS.Resources.InputConfigLoader.JoystickInputJson.JoystickThreshold
  - ECS.Resources.InputConfigLoader.JoystickInputJson.JoystickType
  langs:
  - csharp
  - vb
  name: InputConfigLoader.JoystickInputJson
  nameWithType: InputConfigLoader.JoystickInputJson
  fullName: ECS.Resources.InputConfigLoader.JoystickInputJson
  type: Class
  source:
    remote:
      path: Resources/InputConfigLoader.cs
      branch: Sprint5
      repo: https://github.com/zehdari/TeamGame
    id: JoystickInputJson
    path: ../Resources/InputConfigLoader.cs
    startLine: 11
  assemblies:
  - ECS
  namespace: ECS.Resources
  syntax:
    content: private class InputConfigLoader.JoystickInputJson
    content.vb: Private Class InputConfigLoader.JoystickInputJson
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: ECS.Resources.InputConfigLoader.JoystickInputJson.JoystickType
  commentId: P:ECS.Resources.InputConfigLoader.JoystickInputJson.JoystickType
  id: JoystickType
  parent: ECS.Resources.InputConfigLoader.JoystickInputJson
  langs:
  - csharp
  - vb
  name: JoystickType
  nameWithType: InputConfigLoader.JoystickInputJson.JoystickType
  fullName: ECS.Resources.InputConfigLoader.JoystickInputJson.JoystickType
  type: Property
  source:
    remote:
      path: Resources/InputConfigLoader.cs
      branch: Sprint5
      repo: https://github.com/zehdari/TeamGame
    id: JoystickType
    path: ../Resources/InputConfigLoader.cs
    startLine: 13
  assemblies:
  - ECS
  namespace: ECS.Resources
  syntax:
    content: public string JoystickType { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property JoystickType As String
  overload: ECS.Resources.InputConfigLoader.JoystickInputJson.JoystickType*
- uid: ECS.Resources.InputConfigLoader.JoystickInputJson.JoystickDirection
  commentId: P:ECS.Resources.InputConfigLoader.JoystickInputJson.JoystickDirection
  id: JoystickDirection
  parent: ECS.Resources.InputConfigLoader.JoystickInputJson
  langs:
  - csharp
  - vb
  name: JoystickDirection
  nameWithType: InputConfigLoader.JoystickInputJson.JoystickDirection
  fullName: ECS.Resources.InputConfigLoader.JoystickInputJson.JoystickDirection
  type: Property
  source:
    remote:
      path: Resources/InputConfigLoader.cs
      branch: Sprint5
      repo: https://github.com/zehdari/TeamGame
    id: JoystickDirection
    path: ../Resources/InputConfigLoader.cs
    startLine: 14
  assemblies:
  - ECS
  namespace: ECS.Resources
  syntax:
    content: public string JoystickDirection { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property JoystickDirection As String
  overload: ECS.Resources.InputConfigLoader.JoystickInputJson.JoystickDirection*
- uid: ECS.Resources.InputConfigLoader.JoystickInputJson.JoystickThreshold
  commentId: P:ECS.Resources.InputConfigLoader.JoystickInputJson.JoystickThreshold
  id: JoystickThreshold
  parent: ECS.Resources.InputConfigLoader.JoystickInputJson
  langs:
  - csharp
  - vb
  name: JoystickThreshold
  nameWithType: InputConfigLoader.JoystickInputJson.JoystickThreshold
  fullName: ECS.Resources.InputConfigLoader.JoystickInputJson.JoystickThreshold
  type: Property
  source:
    remote:
      path: Resources/InputConfigLoader.cs
      branch: Sprint5
      repo: https://github.com/zehdari/TeamGame
    id: JoystickThreshold
    path: ../Resources/InputConfigLoader.cs
    startLine: 15
  assemblies:
  - ECS
  namespace: ECS.Resources
  syntax:
    content: public float JoystickThreshold { get; set; }
    parameters: []
    return:
      type: System.Single
    content.vb: Public Property JoystickThreshold As Single
  overload: ECS.Resources.InputConfigLoader.JoystickInputJson.JoystickThreshold*
references:
- uid: ECS.Resources
  commentId: N:ECS.Resources
  href: ECS.html
  name: ECS.Resources
  nameWithType: ECS.Resources
  fullName: ECS.Resources
  spec.csharp:
  - uid: ECS
    name: ECS
    href: ECS.html
  - name: .
  - uid: ECS.Resources
    name: Resources
    href: ECS.Resources.html
  spec.vb:
  - uid: ECS
    name: ECS
    href: ECS.html
  - name: .
  - uid: ECS.Resources
    name: Resources
    href: ECS.Resources.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: ECS.Resources.InputConfigLoader.JoystickInputJson.JoystickType*
  commentId: Overload:ECS.Resources.InputConfigLoader.JoystickInputJson.JoystickType
  href: ECS.Resources.InputConfigLoader.JoystickInputJson.html#ECS_Resources_InputConfigLoader_JoystickInputJson_JoystickType
  name: JoystickType
  nameWithType: InputConfigLoader.JoystickInputJson.JoystickType
  fullName: ECS.Resources.InputConfigLoader.JoystickInputJson.JoystickType
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: ECS.Resources.InputConfigLoader.JoystickInputJson.JoystickDirection*
  commentId: Overload:ECS.Resources.InputConfigLoader.JoystickInputJson.JoystickDirection
  href: ECS.Resources.InputConfigLoader.JoystickInputJson.html#ECS_Resources_InputConfigLoader_JoystickInputJson_JoystickDirection
  name: JoystickDirection
  nameWithType: InputConfigLoader.JoystickInputJson.JoystickDirection
  fullName: ECS.Resources.InputConfigLoader.JoystickInputJson.JoystickDirection
- uid: ECS.Resources.InputConfigLoader.JoystickInputJson.JoystickThreshold*
  commentId: Overload:ECS.Resources.InputConfigLoader.JoystickInputJson.JoystickThreshold
  href: ECS.Resources.InputConfigLoader.JoystickInputJson.html#ECS_Resources_InputConfigLoader_JoystickInputJson_JoystickThreshold
  name: JoystickThreshold
  nameWithType: InputConfigLoader.JoystickInputJson.JoystickThreshold
  fullName: ECS.Resources.InputConfigLoader.JoystickInputJson.JoystickThreshold
- uid: System.Single
  commentId: T:System.Single
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.single
  name: float
  nameWithType: float
  fullName: float
  nameWithType.vb: Single
  fullName.vb: Single
  name.vb: Single
