### YamlMime:ManagedReference
items:
- uid: ECS.Components.Animation.SpriteConfig
  commentId: T:ECS.Components.Animation.SpriteConfig
  id: SpriteConfig
  parent: ECS.Components.Animation
  children:
  - ECS.Components.Animation.SpriteConfig.Color
  - ECS.Components.Animation.SpriteConfig.Layer
  - ECS.Components.Animation.SpriteConfig.Origin
  - ECS.Components.Animation.SpriteConfig.SourceRect
  - ECS.Components.Animation.SpriteConfig.Texture
  langs:
  - csharp
  - vb
  name: SpriteConfig
  nameWithType: SpriteConfig
  fullName: ECS.Components.Animation.SpriteConfig
  type: Struct
  source:
    remote:
      path: Components/Animation/SpriteConfig.cs
      branch: Sprint4
      repo: https://github.com/zehdari/TeamGame
    id: SpriteConfig
    path: ../Components/Animation/SpriteConfig.cs
    startLine: 15
  assemblies:
  - ECS
  namespace: ECS.Components.Animation
  syntax:
    content: public struct SpriteConfig
    content.vb: Public Structure SpriteConfig
  inheritedMembers:
  - System.ValueType.Equals(System.Object)
  - System.ValueType.GetHashCode
  - System.ValueType.ToString
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.ReferenceEquals(System.Object,System.Object)
- uid: ECS.Components.Animation.SpriteConfig.Texture
  commentId: F:ECS.Components.Animation.SpriteConfig.Texture
  id: Texture
  parent: ECS.Components.Animation.SpriteConfig
  langs:
  - csharp
  - vb
  name: Texture
  nameWithType: SpriteConfig.Texture
  fullName: ECS.Components.Animation.SpriteConfig.Texture
  type: Field
  source:
    remote:
      path: Components/Animation/SpriteConfig.cs
      branch: Sprint4
      repo: https://github.com/zehdari/TeamGame
    id: Texture
    path: ../Components/Animation/SpriteConfig.cs
    startLine: 17
  assemblies:
  - ECS
  namespace: ECS.Components.Animation
  syntax:
    content: public Texture2D Texture
    return:
      type: Microsoft.Xna.Framework.Graphics.Texture2D
    content.vb: Public Texture As Texture2D
- uid: ECS.Components.Animation.SpriteConfig.SourceRect
  commentId: F:ECS.Components.Animation.SpriteConfig.SourceRect
  id: SourceRect
  parent: ECS.Components.Animation.SpriteConfig
  langs:
  - csharp
  - vb
  name: SourceRect
  nameWithType: SpriteConfig.SourceRect
  fullName: ECS.Components.Animation.SpriteConfig.SourceRect
  type: Field
  source:
    remote:
      path: Components/Animation/SpriteConfig.cs
      branch: Sprint4
      repo: https://github.com/zehdari/TeamGame
    id: SourceRect
    path: ../Components/Animation/SpriteConfig.cs
    startLine: 18
  assemblies:
  - ECS
  namespace: ECS.Components.Animation
  syntax:
    content: public Rectangle SourceRect
    return:
      type: Microsoft.Xna.Framework.Rectangle
    content.vb: Public SourceRect As Rectangle
- uid: ECS.Components.Animation.SpriteConfig.Origin
  commentId: F:ECS.Components.Animation.SpriteConfig.Origin
  id: Origin
  parent: ECS.Components.Animation.SpriteConfig
  langs:
  - csharp
  - vb
  name: Origin
  nameWithType: SpriteConfig.Origin
  fullName: ECS.Components.Animation.SpriteConfig.Origin
  type: Field
  source:
    remote:
      path: Components/Animation/SpriteConfig.cs
      branch: Sprint4
      repo: https://github.com/zehdari/TeamGame
    id: Origin
    path: ../Components/Animation/SpriteConfig.cs
    startLine: 19
  assemblies:
  - ECS
  namespace: ECS.Components.Animation
  syntax:
    content: public Vector2 Origin
    return:
      type: Microsoft.Xna.Framework.Vector2
    content.vb: Public Origin As Vector2
- uid: ECS.Components.Animation.SpriteConfig.Color
  commentId: F:ECS.Components.Animation.SpriteConfig.Color
  id: Color
  parent: ECS.Components.Animation.SpriteConfig
  langs:
  - csharp
  - vb
  name: Color
  nameWithType: SpriteConfig.Color
  fullName: ECS.Components.Animation.SpriteConfig.Color
  type: Field
  source:
    remote:
      path: Components/Animation/SpriteConfig.cs
      branch: Sprint4
      repo: https://github.com/zehdari/TeamGame
    id: Color
    path: ../Components/Animation/SpriteConfig.cs
    startLine: 20
  assemblies:
  - ECS
  namespace: ECS.Components.Animation
  syntax:
    content: public Color Color
    return:
      type: Microsoft.Xna.Framework.Color
    content.vb: Public Color As Color
- uid: ECS.Components.Animation.SpriteConfig.Layer
  commentId: F:ECS.Components.Animation.SpriteConfig.Layer
  id: Layer
  parent: ECS.Components.Animation.SpriteConfig
  langs:
  - csharp
  - vb
  name: Layer
  nameWithType: SpriteConfig.Layer
  fullName: ECS.Components.Animation.SpriteConfig.Layer
  type: Field
  source:
    remote:
      path: Components/Animation/SpriteConfig.cs
      branch: Sprint4
      repo: https://github.com/zehdari/TeamGame
    id: Layer
    path: ../Components/Animation/SpriteConfig.cs
    startLine: 21
  assemblies:
  - ECS
  namespace: ECS.Components.Animation
  syntax:
    content: public DrawLayer Layer
    return:
      type: ECS.Components.Animation.DrawLayer
    content.vb: Public Layer As DrawLayer
references:
- uid: ECS.Components.Animation
  commentId: N:ECS.Components.Animation
  href: ECS.html
  name: ECS.Components.Animation
  nameWithType: ECS.Components.Animation
  fullName: ECS.Components.Animation
  spec.csharp:
  - uid: ECS
    name: ECS
    href: ECS.html
  - name: .
  - uid: ECS.Components
    name: Components
    href: ECS.Components.html
  - name: .
  - uid: ECS.Components.Animation
    name: Animation
    href: ECS.Components.Animation.html
  spec.vb:
  - uid: ECS
    name: ECS
    href: ECS.html
  - name: .
  - uid: ECS.Components
    name: Components
    href: ECS.Components.html
  - name: .
  - uid: ECS.Components.Animation
    name: Animation
    href: ECS.Components.Animation.html
- uid: System.ValueType.Equals(System.Object)
  commentId: M:System.ValueType.Equals(System.Object)
  parent: System.ValueType
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.valuetype.equals
  name: Equals(object)
  nameWithType: ValueType.Equals(object)
  fullName: System.ValueType.Equals(object)
  nameWithType.vb: ValueType.Equals(Object)
  fullName.vb: System.ValueType.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.ValueType.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.equals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.ValueType.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.equals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.ValueType.GetHashCode
  commentId: M:System.ValueType.GetHashCode
  parent: System.ValueType
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.valuetype.gethashcode
  name: GetHashCode()
  nameWithType: ValueType.GetHashCode()
  fullName: System.ValueType.GetHashCode()
  spec.csharp:
  - uid: System.ValueType.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.ValueType.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.gethashcode
  - name: (
  - name: )
- uid: System.ValueType.ToString
  commentId: M:System.ValueType.ToString
  parent: System.ValueType
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.valuetype.tostring
  name: ToString()
  nameWithType: ValueType.ToString()
  fullName: System.ValueType.ToString()
  spec.csharp:
  - uid: System.ValueType.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.ValueType.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.tostring
  - name: (
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.ValueType
  commentId: T:System.ValueType
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.valuetype
  name: ValueType
  nameWithType: ValueType
  fullName: System.ValueType
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Microsoft.Xna.Framework.Graphics.Texture2D
  commentId: T:Microsoft.Xna.Framework.Graphics.Texture2D
  parent: Microsoft.Xna.Framework.Graphics
  isExternal: true
  name: Texture2D
  nameWithType: Texture2D
  fullName: Microsoft.Xna.Framework.Graphics.Texture2D
- uid: Microsoft.Xna.Framework.Graphics
  commentId: N:Microsoft.Xna.Framework.Graphics
  isExternal: true
  name: Microsoft.Xna.Framework.Graphics
  nameWithType: Microsoft.Xna.Framework.Graphics
  fullName: Microsoft.Xna.Framework.Graphics
  spec.csharp:
  - uid: Microsoft
    name: Microsoft
    isExternal: true
  - name: .
  - uid: Microsoft.Xna
    name: Xna
    isExternal: true
  - name: .
  - uid: Microsoft.Xna.Framework
    name: Framework
    isExternal: true
  - name: .
  - uid: Microsoft.Xna.Framework.Graphics
    name: Graphics
    isExternal: true
  spec.vb:
  - uid: Microsoft
    name: Microsoft
    isExternal: true
  - name: .
  - uid: Microsoft.Xna
    name: Xna
    isExternal: true
  - name: .
  - uid: Microsoft.Xna.Framework
    name: Framework
    isExternal: true
  - name: .
  - uid: Microsoft.Xna.Framework.Graphics
    name: Graphics
    isExternal: true
- uid: Microsoft.Xna.Framework.Rectangle
  commentId: T:Microsoft.Xna.Framework.Rectangle
  parent: Microsoft.Xna.Framework
  isExternal: true
  name: Rectangle
  nameWithType: Rectangle
  fullName: Microsoft.Xna.Framework.Rectangle
- uid: Microsoft.Xna.Framework
  commentId: N:Microsoft.Xna.Framework
  isExternal: true
  name: Microsoft.Xna.Framework
  nameWithType: Microsoft.Xna.Framework
  fullName: Microsoft.Xna.Framework
  spec.csharp:
  - uid: Microsoft
    name: Microsoft
    isExternal: true
  - name: .
  - uid: Microsoft.Xna
    name: Xna
    isExternal: true
  - name: .
  - uid: Microsoft.Xna.Framework
    name: Framework
    isExternal: true
  spec.vb:
  - uid: Microsoft
    name: Microsoft
    isExternal: true
  - name: .
  - uid: Microsoft.Xna
    name: Xna
    isExternal: true
  - name: .
  - uid: Microsoft.Xna.Framework
    name: Framework
    isExternal: true
- uid: Microsoft.Xna.Framework.Vector2
  commentId: T:Microsoft.Xna.Framework.Vector2
  parent: Microsoft.Xna.Framework
  isExternal: true
  name: Vector2
  nameWithType: Vector2
  fullName: Microsoft.Xna.Framework.Vector2
- uid: Microsoft.Xna.Framework.Color
  commentId: T:Microsoft.Xna.Framework.Color
  parent: Microsoft.Xna.Framework
  isExternal: true
  name: Color
  nameWithType: Color
  fullName: Microsoft.Xna.Framework.Color
- uid: ECS.Components.Animation.DrawLayer
  commentId: T:ECS.Components.Animation.DrawLayer
  parent: ECS.Components.Animation
  href: ECS.Components.Animation.DrawLayer.html
  name: DrawLayer
  nameWithType: DrawLayer
  fullName: ECS.Components.Animation.DrawLayer
