### YamlMime:ManagedReference
items:
- uid: ECS.Components.UI.HUDConfig
  commentId: T:ECS.Components.UI.HUDConfig
  id: HUDConfig
  parent: ECS.Components.UI
  children:
  - ECS.Components.UI.HUDConfig.Frame
  - ECS.Components.UI.HUDConfig.Lives
  - ECS.Components.UI.HUDConfig.LivesOffset
  - ECS.Components.UI.HUDConfig.LivesPosition
  - ECS.Components.UI.HUDConfig.TextPosition
  langs:
  - csharp
  - vb
  name: HUDConfig
  nameWithType: HUDConfig
  fullName: ECS.Components.UI.HUDConfig
  type: Struct
  source:
    remote:
      path: Components/UI/HUDConfig.cs
      branch: Sprint3
      repo: https://github.com/zehdari/TeamGame
    id: HUDConfig
    path: ../Components/UI/HUDConfig.cs
    startLine: 1
  assemblies:
  - ECS
  namespace: ECS.Components.UI
  syntax:
    content: public struct HUDConfig
    content.vb: Public Structure HUDConfig
  inheritedMembers:
  - System.ValueType.Equals(System.Object)
  - System.ValueType.GetHashCode
  - System.ValueType.ToString
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.ReferenceEquals(System.Object,System.Object)
- uid: ECS.Components.UI.HUDConfig.Frame
  commentId: F:ECS.Components.UI.HUDConfig.Frame
  id: Frame
  parent: ECS.Components.UI.HUDConfig
  langs:
  - csharp
  - vb
  name: Frame
  nameWithType: HUDConfig.Frame
  fullName: ECS.Components.UI.HUDConfig.Frame
  type: Field
  source:
    remote:
      path: Components/UI/HUDConfig.cs
      branch: Sprint3
      repo: https://github.com/zehdari/TeamGame
    id: Frame
    path: ../Components/UI/HUDConfig.cs
    startLine: 3
  assemblies:
  - ECS
  namespace: ECS.Components.UI
  syntax:
    content: public string Frame
    return:
      type: System.String
    content.vb: Public Frame As String
- uid: ECS.Components.UI.HUDConfig.Lives
  commentId: F:ECS.Components.UI.HUDConfig.Lives
  id: Lives
  parent: ECS.Components.UI.HUDConfig
  langs:
  - csharp
  - vb
  name: Lives
  nameWithType: HUDConfig.Lives
  fullName: ECS.Components.UI.HUDConfig.Lives
  type: Field
  source:
    remote:
      path: Components/UI/HUDConfig.cs
      branch: Sprint3
      repo: https://github.com/zehdari/TeamGame
    id: Lives
    path: ../Components/UI/HUDConfig.cs
    startLine: 4
  assemblies:
  - ECS
  namespace: ECS.Components.UI
  syntax:
    content: public string Lives
    return:
      type: System.String
    content.vb: Public Lives As String
- uid: ECS.Components.UI.HUDConfig.LivesPosition
  commentId: F:ECS.Components.UI.HUDConfig.LivesPosition
  id: LivesPosition
  parent: ECS.Components.UI.HUDConfig
  langs:
  - csharp
  - vb
  name: LivesPosition
  nameWithType: HUDConfig.LivesPosition
  fullName: ECS.Components.UI.HUDConfig.LivesPosition
  type: Field
  source:
    remote:
      path: Components/UI/HUDConfig.cs
      branch: Sprint3
      repo: https://github.com/zehdari/TeamGame
    id: LivesPosition
    path: ../Components/UI/HUDConfig.cs
    startLine: 5
  assemblies:
  - ECS
  namespace: ECS.Components.UI
  syntax:
    content: public Vector2 LivesPosition
    return:
      type: Microsoft.Xna.Framework.Vector2
    content.vb: Public LivesPosition As Vector2
- uid: ECS.Components.UI.HUDConfig.LivesOffset
  commentId: F:ECS.Components.UI.HUDConfig.LivesOffset
  id: LivesOffset
  parent: ECS.Components.UI.HUDConfig
  langs:
  - csharp
  - vb
  name: LivesOffset
  nameWithType: HUDConfig.LivesOffset
  fullName: ECS.Components.UI.HUDConfig.LivesOffset
  type: Field
  source:
    remote:
      path: Components/UI/HUDConfig.cs
      branch: Sprint3
      repo: https://github.com/zehdari/TeamGame
    id: LivesOffset
    path: ../Components/UI/HUDConfig.cs
    startLine: 6
  assemblies:
  - ECS
  namespace: ECS.Components.UI
  syntax:
    content: public Vector2 LivesOffset
    return:
      type: Microsoft.Xna.Framework.Vector2
    content.vb: Public LivesOffset As Vector2
- uid: ECS.Components.UI.HUDConfig.TextPosition
  commentId: F:ECS.Components.UI.HUDConfig.TextPosition
  id: TextPosition
  parent: ECS.Components.UI.HUDConfig
  langs:
  - csharp
  - vb
  name: TextPosition
  nameWithType: HUDConfig.TextPosition
  fullName: ECS.Components.UI.HUDConfig.TextPosition
  type: Field
  source:
    remote:
      path: Components/UI/HUDConfig.cs
      branch: Sprint3
      repo: https://github.com/zehdari/TeamGame
    id: TextPosition
    path: ../Components/UI/HUDConfig.cs
    startLine: 7
  assemblies:
  - ECS
  namespace: ECS.Components.UI
  syntax:
    content: public Vector2 TextPosition
    return:
      type: Microsoft.Xna.Framework.Vector2
    content.vb: Public TextPosition As Vector2
references:
- uid: ECS.Components.UI
  commentId: N:ECS.Components.UI
  href: ECS.html
  name: ECS.Components.UI
  nameWithType: ECS.Components.UI
  fullName: ECS.Components.UI
  spec.csharp:
  - uid: ECS
    name: ECS
    href: ECS.html
  - name: .
  - uid: ECS.Components
    name: Components
    href: ECS.Components.html
  - name: .
  - uid: ECS.Components.UI
    name: UI
    href: ECS.Components.UI.html
  spec.vb:
  - uid: ECS
    name: ECS
    href: ECS.html
  - name: .
  - uid: ECS.Components
    name: Components
    href: ECS.Components.html
  - name: .
  - uid: ECS.Components.UI
    name: UI
    href: ECS.Components.UI.html
- uid: System.ValueType.Equals(System.Object)
  commentId: M:System.ValueType.Equals(System.Object)
  parent: System.ValueType
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.valuetype.equals
  name: Equals(object)
  nameWithType: ValueType.Equals(object)
  fullName: System.ValueType.Equals(object)
  nameWithType.vb: ValueType.Equals(Object)
  fullName.vb: System.ValueType.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.ValueType.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.equals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.ValueType.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.equals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.ValueType.GetHashCode
  commentId: M:System.ValueType.GetHashCode
  parent: System.ValueType
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.valuetype.gethashcode
  name: GetHashCode()
  nameWithType: ValueType.GetHashCode()
  fullName: System.ValueType.GetHashCode()
  spec.csharp:
  - uid: System.ValueType.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.ValueType.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.gethashcode
  - name: (
  - name: )
- uid: System.ValueType.ToString
  commentId: M:System.ValueType.ToString
  parent: System.ValueType
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.valuetype.tostring
  name: ToString()
  nameWithType: ValueType.ToString()
  fullName: System.ValueType.ToString()
  spec.csharp:
  - uid: System.ValueType.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.ValueType.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.tostring
  - name: (
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.ValueType
  commentId: T:System.ValueType
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.valuetype
  name: ValueType
  nameWithType: ValueType
  fullName: System.ValueType
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: Microsoft.Xna.Framework.Vector2
  commentId: T:Microsoft.Xna.Framework.Vector2
  parent: Microsoft.Xna.Framework
  isExternal: true
  name: Vector2
  nameWithType: Vector2
  fullName: Microsoft.Xna.Framework.Vector2
- uid: Microsoft.Xna.Framework
  commentId: N:Microsoft.Xna.Framework
  isExternal: true
  name: Microsoft.Xna.Framework
  nameWithType: Microsoft.Xna.Framework
  fullName: Microsoft.Xna.Framework
  spec.csharp:
  - uid: Microsoft
    name: Microsoft
    isExternal: true
  - name: .
  - uid: Microsoft.Xna
    name: Xna
    isExternal: true
  - name: .
  - uid: Microsoft.Xna.Framework
    name: Framework
    isExternal: true
  spec.vb:
  - uid: Microsoft
    name: Microsoft
    isExternal: true
  - name: .
  - uid: Microsoft.Xna
    name: Xna
    isExternal: true
  - name: .
  - uid: Microsoft.Xna.Framework
    name: Framework
    isExternal: true
