name: Build and Deploy DocFX to GitHub Pages

on:
  push:
    branches:
      - Sprint3

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Install DocFX
      run: dotnet tool install -g docfx

    - name: Build Documentation
      run: docfx DocFX/docfx.json

    - name: Move Built Site to Root
      run: mv DocFX/_site/* .

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .
        publish_branch: gh-pages
        cname: ""  # Ensure no CNAME is set
